Repository wecode-bootcamp-korea/fullstack2-1st-dashincode-backend, pull requests merged in 2021-10, with the labels that each got.

#10 Add: 초기 세팅 완료
  .vscode/setting.json
  app.js
  controllers/cartController.js
  controllers/categoryContoller.js
  controllers/commentContoller.js
  controllers/index.js
  controllers/likeController.js
  controllers/loginController.js
  controllers/productController.js
  controllers/signupController.js
  middlewares/auth.js
  middlewares/validation.js
  models/cartDao.js
  models/categoryDao.js
  models/commentDao.js
  models/index.js
  models/likeDao.js
  models/loginDao.js
  models/productDao.js
  models/signupDao.js
  package-lock.json
  package.json
  prisma/index.js
  prisma/migrations/20211009034506_init/migration.sql
  prisma/migrations/20211009040158_re_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  routes/cartRouter.js
  routes/categoryRouter.js
  routes/commentRouter.js
  routes/index.js
  routes/likeRouter.js
  routes/loginRouter.js
  routes/productRouter.js
  routes/signupRouter.js
  server.js
  services/cartService.js
  services/categoryService.js
  services/commentService.js
  services/index.js
  services/likeService.js
  services/loginService.js
  services/productService.js
  services/signupService.js
  utils/wrapAsync.js
Labels: Status: Accepted

#19 [김지현] comment API 구현중
  controllers/cartController.js
  controllers/categoryController.js
  models/cartDao.js
  models/categoryDao.js
  models/commentDao.js
  models/likeDao.js
  models/loginDao.js
  models/productDao.js
  models/signupDao.js
  routes/commentRouter.js
  services/categoryServices.js
  services/likeServices.js
Labels: Status: 기능 구현 중

#12 [고원구]로그인 API, 토큰검사 MiddleWare 작성
  app.js
  controllers/categoryController.js
  controllers/loginController.js
  middlewares/auth.js
  models/loginDao.js
  routes/index.js
  routes/loginRouter.js
  services/categoryServices.js
  services/loginServices.js
  utils/error.js
Labels: Status: 기능 구현 중

#18 [고원구] signup API 작성
  controllers/signupController.js
  models/signupDao.js
  routes/signupRouter.js
  server.js
  services/signupServices.js
Labels: Status: 기능 구현 중

#24 [고원구] login & signup 컴포넌트 user 컴포넌트로 통합
  controllers/index.js
  controllers/signupController.js
  controllers/userController.js
  middlewares/auth.js
  models/index.js
  models/loginDao.js
  models/userDao.js
  package-lock.json
  package.json
  routes/commentRouter.js
  routes/index.js
  routes/loginRouter.js
  routes/signupRouter.js
  routes/userRouter.js
  services/index.js
  services/signupServices.js
  services/userServices.js
Labels: Status: Accepted

#26 fix: loginController 파일 삭제
  controllers/loginController.js
  controllers/userController.js
Labels: Status: Accepted

#17 [안다빈] like API(미들웨어 머지 이후 테스트 예정)
  controllers/likeController.js
  middlewares/auth.js
  models/likeDao.js
  routes/likeRouter.js
  services/likeServices.js
Labels: Status: Accepted

#31 [김재원] comment API 구현 완료
  .eslintrc.js
  controllers/commentController.js
  controllers/index.js
  controllers/productController.js
  models/commentDao.js
  models/index.js
  models/productDao.js
  routes/commentRouter.js
  routes/index.js
  routes/productRouter.js
  services/commentServices.js
  services/index.js
  services/productServices.js
  services/signupService.js
Labels: Status: 피어 리뷰 요청
